language: c
compiler:
  - gcc
before_script:
  - "sudo apt-get install rlwrap"
  - "sudo apt-get install python-software-properties"
  - "echo 'yes' | sudo add-apt-repository ppa:chris-lea/node.js"
  - "sudo apt-get update"
  - "sudo apt-get install nodejs"
  - "sudo npm install -g node-gyp"
  - "sudo apt-get install libv8-dev"
  - "sudo apt-get install libwebkitgtk-dev"
  - "./autogen.sh && ./configure && make"
script:
  - "make SMOKE=1 check-javascript-test-suite"
  - "make SMOKE=1 ENGINE=jsc check-javascript-test-suite"
  - "make SMOKE=1 ENGINE=v8 check-javascript-test-suite"
